## GitHub Login
#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          github:
#            client-id: cc0e089c4c8b13effa47
#            client-secret: 32ab0ba9a2d5b4b6d7cd3e4f84b68b9e2acb3d06
#
#          # Google Login
##          google:
##            client-id:
##            client-secret:
#
#logging:
#  level:
#    org.springframework.security: TRACE
