spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: skylink
  profiles:
    include:
      - db
      - email
      - security
server:
  port: 8082
  servlet:
    context-path: /skylink

